

#' Title
#'
#' @param id
#' @param label
#' @param sortConditions
#' @param subsetCondition
#' @param annotation
#'
#' @return
#' @export
#'
#' @examples
gatingModuleUI <- function(id, label = "gatingModule", sortConditions,
                           subsetCondition=NULL, annotation){

    ns <- NS(id)

    box(
    tagList(
    h4("Filter Samples"),
    # checkboxGroupInput("panelDisplayPop", label="Show Panel",
    #                    choices=c("1", "3"), selected=c("1","3")),
    #uiOutput(ns("gatingDynamicUI")),
    absolutePanel(id=ns("heatmap"), h4("Population Heatmap (Click on box to see provenance)"),
                  ggvisOutput(ns("populationHeatmap")), top=250, left=0),
    # absolutePanel(id="scheme",imageOutput(ns("pipelineHierarchy")), top=250, left=650),
    absolutePanel(id=ns("gating"),draggable=TRUE,top=0, left=300,
                   fixed=FALSE,
                   style="opacity: 0.8; background-color: white",
                   height=200,width="auto",
                   h4("Gating Scheme (draggable)"),
                   imageOutput(ns("gating"))),
    br(), br(), br(), br(), br()
    ))

}

#' Title
#'
#' @param input - shiny module input object
#' @param output - shiny module output object
#' @param session - shiny module session object
#' @param imageDir - relative directory location of "images/" directory generated
#' by plotAllPopulations()
#' @param popTable - populationTable generated by getPopulationsAndZscores
#' @param displayNodes - which gating populations to display in heatmap
#' @param annotation - annotation data.table
#' @param plotObj
#' @param subsetChoices
#'
#' @return
#' @export
#'
#' @examples
gatingModuleOutput <- function(input, output, session,
                               imageDir, popTable, displayNodes, annotation, plotObj,
                               subsetChoices=NULL){

  ns <- session$ns


  popTooltip <- function(x){
    if(is.null(x)) return(NULL)
    #out <- paste0("<img src='data/images/", x$idVar, ".png'></img>")
    plotObj[["gating"]] <- paste0(imageDir, x$idVar, ".png")
    #print(out)
    #out
    x$idVar
  }

  pngGraph <- reactive({
    return(plotObj[["gating"]])
  })

  output$gating <- renderImage({
    list(src = pngGraph(),
         contentType = "image/png"
    )
  },deleteFile=FALSE)


  # populationHeatmap <- reactive({
  #
  #   indata <- na.omit(popTable[annotateSelect()])
  #   #print(indata)
  #   #print(annotateSelect())
  #   populationHeatmapPlot(indata, displayNodes) #%>%
  #     #bind_shiny(ns("populationHeatmap"),session = getDefaultReactiveDomain()[["parent"]])
  #
  #   #if(length(Samples())==0){
  #   #  domX <- domXspare
  #   #}else{
  #   #  domX <- Samples()
  #   #}
  # })

  populationHeatmap <- reactive({

    popHeatmap(popTable, annotation, mapVar=c("name"="FCSFiles")) %>%
      #add interactive tooltip
      add_tooltip(popTooltip,on="click")

  })

  populationHeatmap %>%
    bind_shiny(ns("populationHeatmap"), session=session)
  #bind_shiny("plot-plot", session = getDefaultReactiveDomain()[["parent"]])
}

padMissingValues <- function(popTable){
  populations <- unique(as.character(popTable[["Population"]]))
  samples <- unique(as.character(popTable[["notation"]]))
  expand.grid(populations, samples)

}

#' Title
#'
#' @param data
#' @param annotation
#' @param mapVar
#'
#' @return
#' @export
#'
#' @examples
popHeatmap <- function(data, annotation, mapVar=c("name"="FCSFiles")){

  dataNew <- data[annotation, on=mapVar]
  dataNew <- data[!is.na(percentPop)]

  domY <- unique(as.character(data[["Population"]]))
  displayNodes <- domY
  noMarkers <- length(displayNodes)

  domX <- unique(as.character(data[["name"]]))
  noSamples <- length(domX)

  Green <- colorRampPalette(c("green","green4"))
  Red <- colorRampPalette(c("red4","red"))

  levs <- sort(unique(round(data$zscore)))

  #print(levs)

  belowAverage <- length(which(levs < 0))
  aboveAverage <- length(which(levs > 0))

  pal <- c(Green(belowAverage), "000000", Red(aboveAverage))

  #pal <- c(Blue(3), "#E5E5E5", Orange(6))

  dataNew[Population %in% displayNodes] %>%
    #mutate()
    #filter(as.character(Population) %in% displayNodes) %>%
    ggvis(x=~name,y= ~Population, fill=~factor(round(zscore))) %>%
    #ggvis(x=~name,y= ~Population, fill=~factor(round(Count))) %>%
    layer_rects(height = band(), width = band(), key:=~idVar) %>%
    scale_ordinal('fill',range = pal) %>%
    add_axis("x", properties = axis_props(labels = list(angle = 270)), orient="top",
             title_offset = 120, tick_padding=40, title="Sample") %>%
    add_axis("y", orient="left", title_offset = 100) %>%
    #add_tooltip(popTooltip,on="click") %>%
    #add_tooltip(popInfoTooltip, on="hover") %>%
    scale_nominal("y", padding = 0, points = FALSE, domain = displayNodes) %>%
    #scale_nominal("x", padding = 0, points = FALSE, domain = domX) %>%
    scale_nominal("x", padding = 0, points = FALSE) %>%
    layer_text(text:=~signif(percentPop,digits=2), stroke:="darkgrey", align:="left",
               baseline:="top", dx := 5, dy:=5) %>%
    set_options(width= max(c(60 * (noSamples), 600)), height= max(60 *(noMarkers), 700))

}



#' Title
#'
#' @param data
#' @param annotation
#' @param mapVar
#'
#' @return
#' @export
#'
#' @examples
popHeatmapGG <- function(data, annotation, mapVar=c("name"="FCSFiles")){

  dataNew <- data[annotation, on=mapVar]
  dataNew <- data[!is.na(percentPop)]

  domY <- unique(as.character(data[["Population"]]))
  displayNodes <- domY
  noMarkers <- length(displayNodes)

  domX <- unique(as.character(data[["name"]]))
  noSamples <- length(domX)

  Green <- colorRampPalette(c("green","green4"))
  Red <- colorRampPalette(c("red4","red"))

  levs <- sort(unique(round(data$zscore)))

  #print(levs)

  belowAverage <- length(which(levs < 0))
  aboveAverage <- length(which(levs > 0))

  pal <- c(Green(belowAverage), "000000", Red(aboveAverage))

  #pal <- c(Blue(3), "#E5E5E5", Orange(6))

  dataNew[Population %in% displayNodes] %>%
    mutate(fillVals = round(zscore)) %>%
    ggplot(aes_string(x="name", y="Population", fill="fillVals")) +
    geom_tile(aes(colour="black")) + scale_fill_gradient2(low = "Blue", mid="White", high = "Orange") +
    scale_y_discrete()

}
